spring.application.name=baligh-api
server.port=8080

# الربط مع MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/balighdb?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rinad12217649@
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false



spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-swallow-size=200MB
server.tomcat.max-http-form-post-size=200000000
app.storage.upload-dir=uploads/
twilio.account-sid=AC415409dd3100914854f5103b16257bd0
twilio.auth-token=784840f051de860728346bebc9c02e00
twilio.verify-service-sid=VAc567cdd5b08f3f90881ab902b3a1bb11
app.base-url=http://192.168.1.10:8080
